### ISSUE TITLE
Params with empty value should not display =

### ISSUE THREAD

**Issue by martinos** [balena/elixir-sippet#14]
I am receiving request that has a `Via` header that has a rport flag. Here is the original header

```
Via: SIP/2.0/UDP 205.205.74.6:5060;rport;branch=z9hG4bK-26320-1-0
```

When I return the response, the `Via` header is serialized this way:

```
Via: SIP/2.0/UDP 205.205.74.6:5060;rport=;received=127.0.0.1;branch=z9hG4bK-26320-1-0
```

Note that the `rport=` param is invalid. https://www.tech-invite.com/fo-abnf/tinv-fo-abnf-sip-h-via.html#via-params. 

I think that the value of a parameter cannot be an empty string.

**Comment by balena** [comment]
@martinos : recall that when you return a response you should set the `rport` parameter with the source port of the packet you received the message as per RFC 3581. But in any case, I'm now honoring what you said: if you really want to forward a message without setting the rport parameter, the implementation will not bother you.
