### ISSUE TITLE
When I try to run test - Compilation fails on Mac

### ISSUE THREAD

**Issue by rvarma1848** [balena/elixir-sippet#21]
cc /Users/krishna/projects/elixir-sippet/c_src/string_piece.o /Users/krishna/projects/elixir-sippet/c_src/utils.o /Users/krishna/projects/elixir-sippet/c_src/parser.o /Users/krishna/projects/elixir-sippet/c_src/tokenizer.o /Users/krishna/projects/elixir-sippet/c_src/prtime.o -arch x86_64 -flat_namespace -undefined suppress -shared -lstdc++ -L /usr/local/Cellar/erlang/23.1.1/lib/erlang/usr/lib -lerl_interface -lei -o /Users/krishna/projects/elixir-sippet/priv/sippet_nif.so
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/krishna/projects/elixir-sippet/priv/sippet_nif.so] Error 1

**Comment by balena** [comment]
Problem solved in 1.0.8
