### ISSUE TITLE
NIF does not compile on M1 mac

### ISSUE THREAD

**Issue by anamba** [balena/elixir-sippet#23]
It was easy enough to fix though, I went into `c_src/Makefile` and removed the `-arch x86_64`s under `ifeq ($(UNAME_SYS), Darwin)`, then did a `make clean && make`. That seemed to get things working (I think, I haven't played around with this too much yet).

**Comment by balena** [comment]
Hi @anamba, fixed in https://github.com/balena/elixir-sippet/commit/97dd7e20dc2910925f419c0eab06bb32eb1b441e.
