### ISSUE TITLE
Improve explanation for the Sippet.send function in README.md

### ISSUE THREAD

**Issue by martinos** [balena/elixir-sippet#24]
I am trying migrate my app to the latest version of Sippet and I don't understand how to send a response back to the caller. 

When I read the README file, I see

```elixir
Sippet.send(:sippet, request)
```

I don't understand what is the `:sippet` atom. Should it be the stack name? 

Prior to the migration my Core module add a function as such:

```elixir
  def receive_request(request, server_key) do
    request
    |> except_to_500(&Auth.auth(&1))
    |> Transactions.send_response(server_key)
  end
```

I am wondering how can I migrate this to the latest version of the library.

**Comment by balena** [comment]
Hi @martinos in the new version `:sippet` in the examples is the stack name. In this new version each stack has a name that you give at your app start:

```elixir
Sippet.start_link(name: :mystack)  # could be :sippet
```

I believe you will want to start it at your supervision tree, so just add it as:
```elixir
children = [
  {Sippet, name: :mystack}
]
```

And like so you just call `Sippet.send/2` passing first argument as the stack name and the second as the message you want to dispatch, be it a request or a response. The stack will figure out how to route it through the stack (passing to server or client transaction etc).

**Comment by martinos** [comment]
In your example I understand well when I see: 

```
  def receive_request(request, _server_key) do
    response =
      request
      |> except_to_500(&Auth.auth(&1))
    Sippet.send(:sippet, response)
  end
  ```
  
  I should replace the `:sippet` for `:mystack`. It should give this instead: 

  ```
  def receive_request(request, _server_key) do
    response =
      request
      |> except_to_500(&Auth.auth(&1))
    Sippet.send(:sippet, response)
  end
  ```

Is there a way to run 2 sippet listening on two different port. I tried and it does not seem to work. 

```
  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      {StirShaken.Tns, []},
      worker(Cachex, [:certs, []]),
      {Sippet, name: :as_stack},
      {Sippet.Transports.UDP, name: :as_stack, port: 5062},
      {Sippet, name: :vs_stack},
      {Sippet.Transports.UDP, name: :vs_stack, port: 5063}
    ]

    opts = [strategy: :one_for_one, name: StirShaken.Supervisor]

    res = Supervisor.start_link(children, opts)
    Sippet.register_core(:as_stack, StirShaken.AsCore)
    Sippet.register_core(:vs_stack, StirShaken.VsCore)
    res
end
```
I didn't touch Elixir for a while so I am a bit confused.

**Comment by balena** [comment]
Yes, your `receive_request/2` function looks fine.

And yes, the purpose of the new `Sippet` version is to permit the creation of multiple stacks just as you mentioned.

**Comment by martinos** [comment]
@balena, I am not sure where to call the `Sippet.register_core` function. Can you help me on that ?

**Comment by balena** [comment]
Closed as no new activity has been registered. Please open a new issue if the problem persists.
