### ISSUE TITLE
:from does not have tag

### ISSUE THREAD

**Issue by martinos** [balena/elixir-sippet#5]
When I send an `OPTION` request to the server using `sipsak`

```
sipsak -vv -c sip:coucou@isptelecom.net -s sip:nobody@localhost
```
I get the following warning from the server:

```
discarded request, ":from does not have tag"
```

I looked at the source code and it seems that the tag is not even parsed. Do I miss something ?

I tried many other request and I had the same issue.

**Comment by martinos** [comment]
It seems that the parser does not work if there is not display_name in the the form header.

**Comment by balena** [comment]
@martinos : I've made some updates on the code to support Elixir 1.8, please double check if it "magically" fixed the issues you got. If not, please read below.

Open a iex terminal with `iex -S mix` and execute the following:

```
        """
        <post your OPTIONS request here>
        """ |> Sippet.Message.parse!()
```

And post your results here. I would like to inspect if the tag wasn't really not parsed...

If you check the unit tests, there is an explicit test for this case you mentioned.
